apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: secrets-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/crichthammer/argo-cd-poc.git
    targetRevision: main
    path: infra/secrets/prod
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
